name: Publish

on:
  release:
    types: [published]
  push:
    branches: 
      - master

jobs:
  release:
    name: Release
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Build
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0) || $(git rev-parse --short HEAD)
          release_name="App-$tag-win-64"

          # Build everything
          dotnet publish --runtime win-x64 -c Release -o "$release_name" -p:PublishReadyToRun=false -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true -p:IncludeNativeLibrariesForSelfExtract=true

          # Pack files
          7z a -tzip "${release_name}.zip" "./${release_name}/*"

          # Delete output directory
          rm -r "$release_name"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "App*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
